dataset: cheese
debug: false
use_scratch: true        # set to false for local runs
scratch_base: /beegfs/HPCscratch
debug_reads_short: 100000
debug_reads_long: 5000
debug_seed: 42
vamb:
  prod:
    minfasta: 200000
    mincontigs: 2000
    batchsize: 256
  debug:
    minfasta: 20
    mincontigs: 100
    batchsize: 8
metabinner:
    min_contig_len: 1000
    kmer_size: 4
threads: 16
long_read_technology: pacbio   # pacbio | nanopore (human_gut_II, activated_sludge)
binning_tools:
  - metabat2 #works
  - maxbin2 #works
  - concoct #works
  #- vamb     #appears to not work in debug, still some errors in cheese
  #- metadecoder  #probably also a debug mode issue
  #- binny #looks incredible complicated to set up
  # - metabinner #slightly harder to install
  - semibin2 #works
  - comebin #currently with hg2 # should work
  
hg38_index: data/human_assembly/bow2_idx/GRCh38_index
remove_human_reads: false
