dataset: debug
debug: true
debug_reads_short: 100000
debug_reads_long: 5000
debug_seed: 42
vamb:
  prod:
    minfasta: 200000
    mincontigs: 2000
    batchsize: 256
  debug:
    minfasta: 20
    mincontigs: 100
    batchsize: 8
threads: 16
long_read_technology: pacbio   # pacbio | nanopore (human_gut_II, activated_sludge)
binning_tools:
  - metabat2
  - maxbin2
  - concoct
hg38_index: data/human_assembly/bow2_idx/GRCh38_index
remove_human_reads: false
